### ISSUE TITLE
Not streaming 

### ISSUE THREAD

**Issue by vagi8** [ramonus/flask-video-stream#1]
Hey !
I was able to successfully run the code.
taking pictures was working fine. But streaming was not happening.
When i tried to debug it using VS Code, i put a breakpoint at this line (frame=..)
```
frame = camera.get_frame()
yield (b'--frame\r\n'b'Content-Type: image/png\r\n\r\n' + frame + b'\r\n\r\n')
```
then after yielding it was showing the picture. then again i continued the debug and nothing was loading. I dont seem to understand the problem. Do we need to add some kind of js for it work ??

**Comment by ramonus** [comment]
Can you give me more explanation, does it show a "no image available" text when accessing the stream page?

**Comment by vagi8** [comment]
Hey ! it automatically started working after a while. i am closing this issue now
