### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by AxelGard** [ramonus/flask-video-stream#3]
Hi Ramonus,

It seems like you don't have a license for this project.  
I would like to use this project, but I need to know the  **what license** the project is under. 

If you are not sure what license to use I would recommend that you use [MIT](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository). 
There is a default template built into GitHub for this.

**Comment by AxelGard** [comment]
I made a PR for an MIT license

**Comment by ramonus** [comment]
Thanks,
I merged it!
