### ISSUE TITLE
Stream endless load - local issue

### ISSUE THREAD

**Issue by Noki9054** [ramonus/flask-video-stream#5]
Streaming on localhost and the 192 address seems to endless load, even when I change port to be public it doesnt work on the host server. Although, when I use my phone and go to the 192 address, the stream works just fine...on mobile. I go to one of my other pc's and load the 192 address, I get the same problem as the host server, endless load for the stream output. But not once having this problem on mobile -> wifi/externally so long as I was able to see it, it worked on mobile.

But not once have I managed to make it work on the host pc, or locally from a different pc without setting the port to be open externally while using a pc. But somehow works on mobile just fine.

When clicking stream it also seems like it long polls both tabs, to the point where I have to close them both, then go back to the url in new tabs because of the endless buffering/loading

**Comment by ramonus** [comment]
It seems weird that it doesn't allow you to connect to from the same computer.
Can you please post the contents of logs/logfile.log after running the server and trying to connect using the same computer?
It can help knowing what happened.

**Comment by ramonus** [comment]
Closing this as there's no response, feel free to reopen if needed

**Comment by x1mus** [comment]
Hello !
I'm having the same problem right now.
Whenever I'm trying to access the streaming page with the actual IP of my host : 192.168.x.x for example the page keeps loading endlessly.

`2021-05-16 17:10:26,367 [DEBUG] __main__:: Requested stream page
2021-05-16 17:10:26,480 [DEBUG] __main__:: Starting stream
2021-05-16 17:10:33,636 [DEBUG] __main__:: Requested stream page
2021-05-16 17:11:55,281 [DEBUG] __main__:: Requested stream page
2021-05-16 17:12:00,562 [DEBUG] __main__:: Requested stream page`

The three last attempts shows that the stream does not start. It just tries to load the page.
